dist: trusty
addons:
  chrome: stable

language: php

php:
  - 7.2
  - 7.3
  - 7.4

sudo: false

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
- vendor/bin/phpunit
